name: deploy-container
on:
   push:
     branches:
       - master
     paths:
       - 'packages/container/\*'

defaults:
    run: |
          echo Add other actions to build,
          echo test, and deploy your project.

